Remove jdbc.rake, causing LoadError on Travis
    LoadError: no such file to load -- jdbc_adapter

Tasks should now defined by Railtie:
https://github.com/jruby/activerecord-jdbc-adapter/blob/master/rails_generators/templates/lib/tasks/jdbc.rake#L6

Signed-off-by: Alex Coles <alex@alexbcoles.com>